frontend/controllers/CartController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
// use common\models\Category;
use common\models\Product;
use yii\web\Session; //класс по раюоте с сессиями
use frontend\models\Cart; //


/**
 * CartController
*/
class CartController extends Controller {

    public function actionAdd() //добавление товара в корзину
    {

    	$id = Yii::$app->request->post('id'); //принимаем то,что в АЯКСЕ передаеи в посте сюда, А передевали мы idпродукта
    	$qty = 1; //кол-во 
    	$product = Product::findOne($id);

    	$session = new Session; //откоыли сессию
    	$session->open(); //откоыли сессию

    	$cart = new Cart;
		$cart->addToCart($product, $qty);  //вызвали метод Модели который записал данные в сессию

		$this->layout = false; //отменят вывод шаблона main и будет выводиться толкь точ то в этом именно виде
		return $this->render('cart-modal', ['session'=>$_SESSION['cart'] ]);

    }


    public function actionClear() //очищаем корзину (удаляем сессию)
    {
    	$session = new Session; //откоыли сессию
    	$session->open(); //откоыли сессию
		$session->remove('cart');
		$session->remove('sum');

		$this->layout = false; //отменят вывод шаблона main и будет выводиться толкь точ то в этом именно виде
		return $this->render('cart-modal', ['session'=>[]]);
    }



    public function actionDel() //удаляем товар одиночный из корзины
    {
    	$id = Yii::$app->request->post('id'); //принимаем то,что в АЯКСЕ передаеи в посте сюда, А передевали мы idпродукта
    	$session = new Session; //откоыли сессию
    	$session->open(); //откоыли сессию
		$cart = new Cart;

		$cart->changeCart($id);
		$this->layout = false; //отменят вывод шаблона main и будет выводиться толкь точ то в этом именно виде
		return $this->render('cart-modal', ['session'=>$_SESSION['cart'] ]);
    }


    public function actionShow() //
    {
      	$session = new Session; //откоыли сессию
    	$session->open(); //откоыли сессию
		$this->layout = false; //отменят вывод шаблона main и будет выводиться толкь точ то в этом именно виде
		return $this->render('cart-modal', ['session'=>$_SESSION['cart'] ]);
    }


}  //__/class CartController

frontend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert; 
use common\widgets\CategoryWidget; //Y2
use yii\bootstrap\Modal;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label' => 'About', 'url' => ['/site/about']],
        ['label' => 'Contact', 'url' => ['/site/contact']],
        //['label' => '>TEST<', 'url' => ['/test/index']],
        ['label' => '>CarT SHOW<', 'url' => ['/cart/show'], 'options'=>['class'=>'showCart'],
    ]];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Signup', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <div class="row">
      <!--Y1-->   
            <div class="col-md-4">
                <?php echo CategoryWidget::widget(); ?>
            </div>
     
            <div class="col-md-8">
                       <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?> 
            </div>
<!--/Y1--> 
            </div>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php 
Modal::begin([ //Y34
    'header'=>'<h2>Backet</h2>',
    'id'=>'cart',
    'size'=>'modal-lg',
    'footer'=>'<button class="btn btn-default" data-dismiss="modal"> Продолжить покупки </button> 
    <a href="/order/view" class="btn btn-primary">Оформить заказ</a> <button class="btn btn-warning clear-cart">Очистьть корзину</button>'
    ]);

Modal::end();
?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>